### ISSUE TITLE
problem parsing extra arguments for cluster creation

### ISSUE THREAD

**Issue by jheikki100** [stackhpc/ansible-role-os-container-clusters#3]
The role is not able to parse extra arguments for cluster creation commands.
for example, in the template file that will be passed to the role I have:
`scicore_container_clusters_template_k8s_fedora_atomic_27:
        #  flags:
        #  - "floating-ip-disabled"
  labels: "cgroup_driver=cgroupfs"
  external_network: "{{ scicore_network_cluster_name }}"
  fixed_network: "{{ scicore_network_demo2_vlan_name }}"
  fixed_subnet: "{{ scicore_network_demo2_vlan_name }}"
  master_flavor: "{{ scicore_flavor_m1_medium.name }}"
`
etc...
See the commented part. Since the role template expects key-value pairs, it is not able to parse in variable with right syntax ( --floating-ip-disabled) and parses instead --flags='floating-ip-disabled' which causes the configuring playbook to fail.
Some of the arguments for the command that creates container cluster do not work as key-value pairs, as seen above.

**Comment by markgoddard** [comment]
Hi Jani, your config hasn't rendered too well so it's difficult to see what's going on. Could you try again using triple backticks?

**Comment by jheikki100** [comment]
```scicore_container_clusters_template_k8s_fedora_atomic_27: 
# flags: # - "floating-ip-disabled" 
labels: "cgroup_driver=cgroupfs" 
external_network: "{{ scicore_network_cluster_name }}" 
fixed_network: "{{ scicore_network_demo2_vlan_name }}" 
fixed_subnet: "{{ scicore_network_demo2_vlan_name }}" 
master_flavor: "{{ scicore_flavor_m1_medium.name }}" ```

Since the role template expects key-value pairs, it is not able to parse in variable with right syntax 
( --floating-ip-disabled) and parses instead 
--flags='floating-ip-disabled' which causes the configuring playbook to fail.

Basically there is also a problem in the scicore-config since the dictionary that is parsed has an option that will not be parsed correctly to magnum command-line (--flags). This is originally coming from p3config from SKA (the part with container cluster configuration). 

Regardless, any option that is not key-value type will fail if the template works as it is doing now inside the task on the role. Sorry for a lengthy explanation!

**Comment by markgoddard** [comment]
I think the issue is that we have an outstanding [pull request](https://github.com/stackhpc/ansible-role-os-container-clusters/pull/1) for this feature. We don't often need to change the cluster templates, so this has gone unnoticed, apologies. I've asked Bharat to take a look at it today.

**Comment by jheikki100** [comment]
Ok, good. Let us know if there is a fix available (by now I just did very quick and dirty fix locally and commented out the --flags and added --floating-ip-disabled into the part of the role that takes care of creating the template.
